### ISSUE TITLE
Selfhosted in a home lab

### ISSUE THREAD

**Issue by Nyxalis** [daytonaio/enterprise-demo#44]
Hello!

I want to install daytona on my homelab but I am confused if it's only for enterprise only.
So will I be able to install or no?

Thanks you

**Comment by zzorica** [comment]
Hi @Nyxalis!

For a home lab setup please use OSS version of Daytona. You can find all the info in the repo [here](https://github.com/daytonaio/daytona)

If you find any issues please feel free to open issue in the mentioned repo.

Regards,
Zoran
